### ISSUE TITLE
Error: Cannot find module 'ws'

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee-factory#147]
See https://github.com/ethersphere/gateway-proxy/pull/235

![Screenshot 2022-05-31 at 19 34 20](https://user-images.githubusercontent.com/7974813/171239770-46d9abe0-50bb-46ad-b4a7-1e19dcf40aee.png)

**Comment by AuHau** [comment]
I think that it is not relevant anymore so closing this.
