### ISSUE TITLE
change python to python3 in .sh

### ISSUE THREAD

**Issue by tamas6** [ethersphere/bee-factory#158]
### stuck at install on intel mac with .zsh shell

bee.sh
fairos.sh

**Comment by AuHau** [comment]
Hey,
I am not really sure what are you doing or what are you trying to achieve. Can you please provide more details?

**Comment by tamas6** [comment]
> Hey,
> I am not really sure what are you doing or what are you trying to achieve. Can you please provide more details?

It's a mistaken issue, irrelevant sorry - should have go to [FDS bee-factory](https://github.com/fairDataSociety/bee-factory)
