### ISSUE TITLE
APIs exposed in the gateway, my Rest calls are keeping connected without ever receiving any response

### ISSUE THREAD

**Issue by FedeC87p** [ethersphere/bee-factory#174]
Hi, 

This issue in only for the Gateway with Debug API no problem.

I try to call curl --location --request POST 'http://mynode:1633/pins/280add20af2e4f419abd0852532892ba0d47abc7d3ab90cac4534db7253b70d0' \
--header 'gas-price: 955200000' \
--header 'gas-limit: 1955200000'
from container logs I can't see any log of that request, however the call hangs for several minutes and I have no answer.   i use a Bee Factory on Debian with command:   bee-factory start --detach 1.6.1

i have install a sniffer on mynode and i see:  {"src_host":"mynode","src_port":60216,"dst_host":"xx.xx.xxx.xxx","dst_port":1633,"payload": [80,79,83,84,32,47,112,105,110,115,47,50,56,48,97,100,100,50,48,97,102,50,101,52,102,52,49,57,97,98,100,48,56,53,50,53,51,50,56,57,50,98,97,48,100,52,55,97,98,99,55,100,51,97,98,57,48,99,97,99,52,53,51,52,100,98,55,50,53,51,98,55,48,100,48,32,72,84,84,80,47,49,46,49,13,10,103,97,115,45,112,114,105,99,101,58,32,57,53,53,50,48,48,48,48,48,13,10,103,97,115,45,108,105,109,105,116,58,32,49,57,53,53,50,48,48,48,48,48,13,10,85,115,101,114,45,65,103,101,110,116,58,32,80,111,115,116,109,97,110,82,117,110,116,105,109,101,47,55,46,50,57,46,48,13,10,65,99,99,101,112,116,58,32,42,47,42,13,10,67,97,99,104,101,45,67,111,110,116,114,111,108,58,32,110,111,45,99,97,99,104,101,13,10,80,111,115,116,109,97,110,45,84,111,107,101,110,58,32,99,52,54,101,50,56,51,54,45,100,100,100,52,45,52,97,54,52,45,97,97,56,51,45,101,53,48,53,50,48,97,52,55,101,100,57,13,10,72,111,115,116,58,32,56,57,46,49,52,53,46,49,54,49,46,49,55,48,58,49,54,51,51,13,10,65,99,99,101,112,116,45,69,110,99,111,100,105,110,103,58,32,103,122,105,112,44,32,100,101,102,108,97,116,101,44,32,98,114,13,10,67,111,110,110,101,99,116,105,111,110,58,32,107,101,101,112,45,97,108,105,118,101,13,10,67,111,110,116,101,110,116,45,76,101,110,103,116,104,58,32,48,13,10,13,10]}
so the request i received by node, but after that is like a blocked

**Comment by AuHau** [comment]
Hey,
I am not sure if I understand your problem here. Few questions.

Why are you mentioning "gateway" here? Are you trying to run Bee Factory cluster as a normal Bee's instance? If so then that is not a supported use case! Bee Factory is for spinning local development environment...
 
Are you running the Bee Factory locally? Or why do you have the `mynode` host?
