### ISSUE TITLE
When buy a stamp the batchTTL stays on -1 even if the usable flag switch to true

### ISSUE THREAD

**Issue by luissanchez0305** [ethersphere/bee-factory#200]
When a stamp is bought the `batchTTL` never got updated with proper time to expire.

The `usable`flag is updated and change to true, but the `batchTTL` doesn't

Status shown on _/health_ is 
```
{
    "status": "ok",
    "version": "1.6.0-6ceadd35",
    "apiVersion": "3.0.1",
    "debugApiVersion": "2.0.1"
}
```

**Comment by AuHau** [comment]
Thanks, in the end it turned out we have this already reported 😅 So closing for duplicate of #74
