### ISSUE TITLE
D.s

### ISSUE THREAD

**Issue by Freitag8** [ethersphere/bee-factory#202]

**Comment by Freitag8** [comment]
![Uploading Screenshot_20220921-041408.png…]()

**Comment by Freitag8** [comment]
![Uploading Screenshot_20220921-041408.png…]()

**Comment by Freitag8** [comment]
Daniel

**Comment by agazso** [comment]
Sorry, I am not sure what you are trying to say. The screenshot is also failed to upload. Closing this, feel free to open a new issue with a description and a screenshot.
