### ISSUE TITLE
Error when running migrate:contracts

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-factory#39]
I'm trying to run the migrate:contracts command but I get an error:
```
% npm run migrate:contracts         

> bee-factory@0.0.1 migrate:contracts /Users/attila/Projects/bee-factory
> truffle migrate


Compiling your contracts...
===========================
> Compiling ./contracts/ERC20PresetMinterPauser.sol
> Compiling @openzeppelin/contracts/access/AccessControl.sol
> Compiling @openzeppelin/contracts/math/SafeMath.sol
> Compiling @openzeppelin/contracts/presets/ERC20PresetMinterPauser.sol
> Compiling @openzeppelin/contracts/token/ERC20/ERC20.sol
> Compiling @openzeppelin/contracts/token/ERC20/ERC20Burnable.sol
> Compiling @openzeppelin/contracts/token/ERC20/ERC20Pausable.sol
> Compiling @openzeppelin/contracts/token/ERC20/IERC20.sol
> Compiling @openzeppelin/contracts/utils/Address.sol
> Compiling @openzeppelin/contracts/utils/Context.sol
> Compiling @openzeppelin/contracts/utils/EnumerableSet.sol
> Compiling @openzeppelin/contracts/utils/Pausable.sol
> Artifacts written to /Users/attila/Projects/bee-factory/build/contracts
> Compiled successfully using:
   - solc: 0.6.12+commit.27d51765.Linux.g++

TypeError: Db.connect is not a function
    at Object.save (/Users/attila/Projects/bee-factory/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:115:1)
    at Object.compileAndSave (/Users/attila/Projects/bee-factory/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:100:1)
    at Object.run (/Users/attila/Projects/bee-factory/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:199:1)
    at Command.run (/Users/attila/Projects/bee-factory/node_modules/truffle/build/webpack:/packages/core/lib/command.js:147:1)
Truffle v5.3.6 (core: 5.3.6)
Node v14.16.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bee-factory@0.0.1 migrate:contracts: `truffle migrate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bee-factory@0.0.1 migrate:contracts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/attila/.npm/_logs/2021-06-01T15_24_01_947Z-debug.log
Exit 1
```

**Comment by RealLau** [comment]
Got the same error, @agazso did you resolve it?

**Comment by agazso** [comment]
> Got the same error, @agazso did you resolve it?

Sorry, still no clue what happens. I have another older Mac with Mojave and it works fine there, but on Big Sur I get this error. However this is not the (only) reason because I have seen it working on someone else's Big Sur.

**Comment by RealLau** [comment]
> > Got the same error, @agazso did you resolve it?
> 
> Sorry, still no clue what happens. I have another older Mac with Mojave and it works fine there, but on Big Sur I get this error. However this is not the (only) reason because I have seen it working on someone else's Big Sur.

It's weird. Maybe it's not a system related error, I got this problem on ubuntu14.04, so...still doing more research on this.

**Comment by RealLau** [comment]
@agazso I found a related issue at https://github.com/trufflesuite/truffle/issues/4141, sadly it's still an open issue

**Comment by s2100** [comment]
I meet the same problem and I found a way to fix this:

1. Do not use `npm install` but yarn instead, which can be installed via `npm i -g yarn`;
2. Then install the node dependencies via `yarn install`
3. Now it can be success with `npm run migrate:contracts`

The reason why `npm i` failed may cause by the wrong version of `truffle` install by npm. Hope the dev team fix this.

**Comment by codiak** [comment]
@s2100 Thank you, that resolved underlying issue for me (also on Mac).

**Comment by AuHau** [comment]
With the refactor, building your own Bee Factory images is not really supported anymore, so closing this. (it might be also resolved actually)
