### ISSUE TITLE
Queen node not initalizing

### ISSUE THREAD

**Issue by JSortGarcia** [ethersphere/bee-factory#42]
I have some problems trying to run the bee-factory. I follow the steps mentioned in the readme for setting up the environment. All previous steps seem correct:
```
./scripts/network.sh
./scripts/blockchain.sh
npm run migrate:contracts
npm run supply
```

When I execute ./scripts/bee.sh start, the queen node does not initialize. When I go to the test-queen container logs I see the following:
```
time="2021-06-14T13:29:40Z" level=info msg="version: 0.6.0-67cc8f24"
time="2021-06-14T13:29:40Z" level=warning msg="clef is not enabled; portability and security of your keys is sub optimal"
time="2021-06-14T13:29:40Z" level=info msg="using existing swarm network address: 689a7bc16ea0291977f77b33403a4cd3e776d9a19f47ba0b66634359983d1cd4"
time="2021-06-14T13:29:40Z" level=info msg="swarm public key 03d5f6051105af2bc1dfb657031fc9d10df9be44ed24608e730a9a0cd07c97e906"
time="2021-06-14T13:29:40Z" level=debug msg="using existing libp2p key"
time="2021-06-14T13:29:40Z" level=debug msg="using existing pss key"
time="2021-06-14T13:29:40Z" level=info msg="pss public key 02f20bfb14a31491f8a9aec2dc455be4353733040e921ececcf612aca735b0bc7c"
time="2021-06-14T13:29:40Z" level=info msg="using ethereum address 26234a2ad3ba8b398a762f279b792cfacd536a3f"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11141cb]
```
I am running:
- Docker version 20.10.6, build 370c289
- Ubuntu 20.10

**Comment by agazso** [comment]
The most likely problem I see is that it seems that it runs Bee version `0.6.0-67cc8f24` (which is the default). However it has known stability issues and it is recommended that you are running a more recent version, for example `0.6.2-984dca0a`.

You can do this by changing the value of `BEE_VERSION` to `0.6.0-67cc8f24` in `./scripts/.env` or export the BEE_VERSION in the shell with the new value. Then run again the commands from start.

**Comment by JSortGarcia** [comment]
Yes, the problem was this. Now when running with Bee version 0.6.2 I can run and interact with the environment.

Thanks for your quick answer!
